name: Merge Trackers
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-trackers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Merge Trackers
        run: |
          curl -s https://raw.githubusercontent.com/ngosang/trackerslist/refs/heads/master/trackers_all.txt > list1.txt
          curl -s https://raw.githubusercontent.com/XIU2/TrackersListCollection/refs/heads/master/all.txt > list2.txt
          
          cat list1.txt list2.txt | grep -v '^$' | sort -u | awk '{print $0 "\n"}' > combined_trackers.txt
          rm list1.txt list2.txt

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add combined_trackers.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update combined trackers"
          git push
